language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
#  - pear install pear/PHP_CodeSniffer
#  - wget http://pecl.php.net/get/pecl_http-1.7.6.tgz
#  - tar -xzf pecl_http-1.7.6.tgz
#  - sh -c "cd pecl_http-1.7.6 && phpize && ./configure && make && sudo make install"
#  - echo "extension=http.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
#  - echo "extension=memcached.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer selfupdate
  - composer install
  - phpenv rehash

script: 
  - phpunit --coverage-text --coverage-clover /tmp/thibaud-evaneos/events/coverage.xml
  - ./vendor/bin/phpcs --standard=./phpcs.xml -n --report=gitblame
